title: Brian Daniels
site_caption: "Projects and occasional blogs"
email: test@test.com
description: "Projects and occasional blogs by Brian Daniels"
baseurl: ""
url: "http://briandaniels.me"
twitter_username: bridadan
github_username:  bridadan

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate

# Assests
# NOTE: not actually writing sass, just using it to minify
sass:
    sass_dir: assets/_sass
    style: compressed

# Permalinks
paginate_path: blog/:year-:month-:day/:title
paginate: 10

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
